// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://guajwystcehdbsvaaizq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1YWp3eXN0Y2VoZGJzdmFhaXpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcxODg0MzAsImV4cCI6MjA1Mjc2NDQzMH0.uXzopbFybzEIk-78QasY52FGmaUvWYvni7GVAWbN9uQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);